spring:
  datasource:
    url: ENC(VER/Nq7bzt4U767+uSAaBxViSdgPB4LgFw0itS3P/5cvbzRH43AEY9WeS0SaeXIwdrtehST0MS+opMck+HAtCdd3au9XASGOC63ArVNHq+B3yxOdYIOxMojlQI5XjxpjEzKelnBqpygRuYE71QNOhw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(h1GnL83oDBt4N+/tYDbOwg==)
    password: ENC(UntvDISjC8RO7upb8UJve3RGV94biTa2)

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # hibernate:
      # ddl-auto: create # 스프링부트가 실행될 때마다 실행.SessionFactory가 시작될때 Drop, Create, Alter 종료될때 Drop
    properties:
      hibernate: #콘솔창에서 쿼리문을 잘 보기 위한 설정
        format_sql: true
        show_sql: true
    # Spring boot 2.5.x 버전 이후 부터는 프로젝트 실행 시 data.sql로 데이터를 초기화 시키기 위해서는 spring.jpa.defer-datasource-initialization=true로 설정해주어야 한다.
    # defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    kdh: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: toy_project_key

